os:
- linux
#- osx
language: node_js
node_js:
- node
- 10 # EOL Apr 21
- 8 # EOL Dec 19
- 6 # EOL Apr 19
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 6
before_script:
- git config --global user.name 'CI'
- git config --global user.email 'dummy@example.org'
script:
- yarn test
