os:
- linux
- osx
- windows
dist: xenial
language: node_js
node_js:
- node
- 12 # EOL Apr 2022
- 10 # EOL Apr 2021
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
env:
  global:
    - YARN_GPG=no # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
before_script:
- git config --global user.name 'CI'
- git config --global user.email 'dummy@example.org'
script:
- yarn test
